services:
  mongo:
    image: mongo:latest
    container_name: mymongodb
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: adm
      MONGO_INITDB_ROOT_PASSWORD: 123
  webapp:
    image: provider
    restart: always
    ports:
      - 8080:8080
    links:
      - mongo

